/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import World.Customer;
import World.DateValidator;
import World.ISystemFacade;
import World.Property;
import World.SystemFacade;
import World.Visit;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author adrian
 */
public class AddToVisitingList extends javax.swing.JFrame {
    
    private final Property property;
    private final Customer customer;
    private final JFrame previousWindow;

    /**
     * Creates new form AddToVisitingList
     * @param property
     * @param customer
     * @param previousWindow
     */
    public AddToVisitingList(Property property, Customer customer, JFrame previousWindow) {
        initComponents();
        this.property = property;
        this.customer = customer;
        this.previousWindow = previousWindow;
        ISystemFacade facade = new SystemFacade(); 
        this.PropertyTextField.setText(this.property.getId() + ". " +
                this.property.getType() + " in "+facade.retrieveNameLocation(this.property.getIdLocation()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ScheduleVisitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DateTextField = new javax.swing.JTextField();
        TimeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PropertyTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add to visiting list");

        jLabel2.setText("Date (dd/mm/yyyy)");

        ScheduleVisitButton.setText("Schedule visit");
        ScheduleVisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleVisitButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Time (hh:mm)");

        jLabel3.setText("Property");

        PropertyTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PropertyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(DateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TimeTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(ScheduleVisitButton)
                        .addGap(46, 46, 46)
                        .addComponent(CancelButton)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PropertyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScheduleVisitButton)
                    .addComponent(CancelButton))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScheduleVisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleVisitButtonActionPerformed
        if (validateFields() == true){
            
            String dateTime = DateTextField.getText() + "" + TimeTextField.getText();
            Visit visit = new Visit(this.customer.getId(),this.property.getId(),dateTime);

            ISystemFacade facade = new SystemFacade();
            if(facade.scheduleVisit(visit) == true){
                this.dispose();          
                this.previousWindow.setVisible(true);
            }
        }
    }//GEN-LAST:event_ScheduleVisitButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
        this.previousWindow.setVisible(true);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private boolean validateFields(){
        
        boolean b = true;
        
        if(DateTextField.getText().compareTo("") == 0){      
            b = false; 
            JOptionPane.showMessageDialog(null, "You have to enter a date");   
        }else{
            DateValidator dateValidator = new DateValidator();
            if (dateValidator.validate(DateTextField.getText()) == false){
                b = false;
                JOptionPane.showMessageDialog(null, "Incorrect date");            
            }else{
                try {
                    DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                    Date dateobj = new Date();
                    
                    Date dateText=new SimpleDateFormat("dd/MM/yyyy").parse(DateTextField.getText());
                    
                    if (dateText.compareTo(dateobj) < 0 || dateText.compareTo(dateobj) == 0) {                                         
                        b = false;
                        JOptionPane.showMessageDialog(null, "Invalid date");       
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(AddPhotoWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        if(TimeTextField.getText().compareTo("") == 0){      
            b = false;
             JOptionPane.showMessageDialog(null, "You have to enter the time"); 
        }else{
            if (TimeTextField.getText().matches("([01]?[0-9]|2[0-3]):[0-5][0-9]") == false){
                b = false;
                JOptionPane.showMessageDialog(null, "Time is incorrect");
            }
        }      
        
        return b;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JTextField PropertyTextField;
    private javax.swing.JButton ScheduleVisitButton;
    private javax.swing.JTextField TimeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
