/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import World.Agent;
import World.ISystemFacade;
import World.Property;
import World.SystemFacade;
import java.util.LinkedHashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author adrian
 */
public class AgentWindow extends javax.swing.JFrame {
    
    private final Agent agent;
    private final JFrame LoginWindow;

    /**
     * Creates new form AgentWindow
     * @param agent
     */
    public AgentWindow(Agent agent, JFrame LoginWindow) {
        initComponents();
        this.agent = agent;
        this.LoginWindow = LoginWindow;
        WelcomeLabel.setText("Welcome agent "+this.agent.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        CreateAccountButton = new javax.swing.JButton();
        SignOutButton = new javax.swing.JButton();
        PendientesAprobacionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeLabel.setText("Welcome, agent");

        CreateAccountButton.setText("Create user account");
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountButtonActionPerformed(evt);
            }
        });

        SignOutButton.setText("Sign out");
        SignOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutButtonActionPerformed(evt);
            }
        });

        PendientesAprobacionButton.setText("Ver propiedades pendientes de aprobación");
        PendientesAprobacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendientesAprobacionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CreateAccountButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignOutButton))
                        .addComponent(PendientesAprobacionButton)))
                .addGap(43, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(WelcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAccountButton)
                    .addComponent(SignOutButton))
                .addGap(36, 36, 36)
                .addComponent(PendientesAprobacionButton)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
        this.dispose();
        new CreateUserAccountWindow(this.agent, this).setVisible(true);
    }//GEN-LAST:event_CreateAccountButtonActionPerformed

    private void SignOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutButtonActionPerformed
        this.dispose();
        this.LoginWindow.setVisible(true);
    }//GEN-LAST:event_SignOutButtonActionPerformed

    private void PendientesAprobacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendientesAprobacionButtonActionPerformed
        ISystemFacade facade = new SystemFacade(); 
        
        LinkedHashMap<Integer,Property> listProperties;
        listProperties = facade.buscarPropiedadesPorAprobar();
        
        if (listProperties == null){  
            JOptionPane.showMessageDialog(null, "Problema trayendo las propiedades"); 
        }else if (listProperties.isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "No hay propiedades pendientes de aprobacion"); 
        }else{  
            this.dispose();
            new VerPendientesAprobacionWindow(this.agent,listProperties,this).setVisible(true);
        }
    }//GEN-LAST:event_PendientesAprobacionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JButton PendientesAprobacionButton;
    private javax.swing.JButton SignOutButton;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
