/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import World.Customer;
import World.ISystemFacade;
import World.Location;
import World.SystemFacade;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author adrian
 */
public class CustomerSearchProperties extends javax.swing.JFrame {
    
    private final Customer customer;
    private final JFrame CustomerWindow;

    /**
     * Creates new form CustomerSearchProperties
     * @param customer
     * @param CustomerWindow
     */
    public CustomerSearchProperties(Customer customer, JFrame CustomerWindow) {
        initComponents();
        this.customer = customer;
        this.CustomerWindow = CustomerWindow;
        
        ISystemFacade facade = new SystemFacade(); 
        
        LinkedHashMap<Integer,Location> listLocations;
        listLocations = facade.retrieveLocations();
        
        if (listLocations == null || listLocations.isEmpty() == true){ 
            
            if(listLocations == null){
                JOptionPane.showMessageDialog(null, "Problem retrieving locations. Properties can not be added");
            }else{
                JOptionPane.showMessageDialog(null, "There is not locations registered. Properties can not be added");
            }
            
            this.dispose();
            this.CustomerWindow.setVisible(true);
            
        }else{  
            
            Location location;
        
            Set set = listLocations.entrySet();        
            Iterator iterator = set.iterator();

            while(iterator.hasNext()) {
                Map.Entry mentry = (Map.Entry)iterator.next();               
                location = (Location) mentry.getValue();
                LocationComboBox.addItem(location.getId()+". "+location.getName());            
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NumberRoomsTextField = new javax.swing.JTextField();
        MinimalRentTextField = new javax.swing.JTextField();
        MaximalRentTextField = new javax.swing.JTextField();
        LocationComboBox = new javax.swing.JComboBox<>();
        TypeComboBox = new javax.swing.JComboBox<>();
        AddButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        SelectedLocationsTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Type of the property");

        jLabel2.setText("Number of rooms");

        jLabel3.setText("Minimal desired rent");

        jLabel4.setText("Maximal desired rent");

        jLabel5.setText("Search properties");

        jLabel6.setText("Location (s)");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not specific", "House", "Apartment" }));

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        SelectedLocationsTextField.setEnabled(false);

        jLabel7.setText("Selected");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 177, Short.MAX_VALUE)
                            .addComponent(MaximalRentTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MinimalRentTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumberRoomsTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SelectedLocationsTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddButton)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveButton)))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchButton)
                .addGap(121, 121, 121)
                .addComponent(BackButton)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(NumberRoomsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MinimalRentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MaximalRentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton)
                    .addComponent(RemoveButton))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectedLocationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(BackButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        String location = (String)LocationComboBox.getSelectedItem();              
        int pointIndex = location.indexOf(".");             
        int idLocation = Integer.parseInt(location.substring(0, pointIndex)); 
        
        String previousText = SelectedLocationsTextField.getText();
        
        int numberIndex = location.indexOf(idLocation);  
        
        
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if (this.validateSelection() == true){
            
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        this.CustomerWindow.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        
        String location = (String)LocationComboBox.getSelectedItem();              
        int pointIndex = location.indexOf(".");             
        int idLocation = Integer.parseInt(location.substring(0, pointIndex)); 
        
        String previousText = SelectedLocationsTextField.getText();
        
        if (previousText.compareTo("") == 0){
            SelectedLocationsTextField.setText(previousText+idLocation);
        }else{
            SelectedLocationsTextField.setText(previousText+" , "+idLocation);
        }
        
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSearchProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSearchProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSearchProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSearchProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CustomerSearchProperties().setVisible(true);
            }
        });
    }
    
    private boolean validateFields(){
        
        boolean b = true;
                
        if(NumberRoomsTextField.getText().compareTo("") != 0){  
            
            if (NumberRoomsTextField.getText().matches("[0-9]+") == false){
                b = false;
                JOptionPane.showMessageDialog(null, "Number of rooms can contain only numbers");
            }else{
                if(NumberRoomsTextField.getText().length() > 9){ 
                    b = false;
                    JOptionPane.showMessageDialog(null, "Number of rooms has a maximum lenght of 9 numbers");
                }
            }
        }
        
        if(MinimalRentTextField.getText().compareTo("") != 0){      
           
            if (MinimalRentTextField.getText().matches("[0-9]+") == false){
                b = false;
                JOptionPane.showMessageDialog(null, "Minimal rent can contain only numbers");
            }else{
                if(MinimalRentTextField.getText().length() > 18){ 
                    b = false;
                    JOptionPane.showMessageDialog(null, "Minimal Rent has a maximum lenght of 18 numbers");
                }
            }                
        }
        
        if(MaximalRentTextField.getText().compareTo("") != 0){      
           
            if (MaximalRentTextField.getText().matches("[0-9]+") == false){
                b = false;
                JOptionPane.showMessageDialog(null, "Maximal rent can contain only numbers");
            }else{
                if(MaximalRentTextField.getText().length() > 18){ 
                    b = false;
                    JOptionPane.showMessageDialog(null, "Maximal rent has a maximum lenght of 18 numbers");
                }
            }                
        }
        
        return b;
    }
    
    private boolean validateSelection(){
        
        int selection = 0;
        
        if (this.validateFields() == true){
            
            if ((String)TypeComboBox.getSelectedItem() != "Not specific"){
                selection = 1;
            }
            
            if(NumberRoomsTextField.getText().compareTo("") != 0){
                selection = 1;
            }
            
            if(MinimalRentTextField.getText().compareTo("") != 0 && MaximalRentTextField.getText().compareTo("") !=0){
                selection = 1;
            }else{
                if((MinimalRentTextField.getText().compareTo("") != 0 &&
                        MaximalRentTextField.getText().compareTo("") == 0) ||
                        (MinimalRentTextField.getText().compareTo("") == 0 &&
                        MaximalRentTextField.getText().compareTo("") != 0) ){
                    JOptionPane.showMessageDialog(null, "If you want to use "
                            + "rent like a criteria, is neccesary write an "
                            + "minimal and maximal desired rent ");
                }
            }
            
            if(SelectedLocationsTextField.getText().compareTo("") != 0){
                selection = 1;
            }            
            
            if (selection == 0){
                JOptionPane.showMessageDialog(null, "You have to search using at least a criteria");
                return false;
            }else{
                return true;
            }
            
        }else{
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox<String> LocationComboBox;
    private javax.swing.JTextField MaximalRentTextField;
    private javax.swing.JTextField MinimalRentTextField;
    private javax.swing.JTextField NumberRoomsTextField;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SelectedLocationsTextField;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
